In [93]:
import pandas as pd
from sklearn.tree import DecisionTreeClassifier #comes with decisionlearn library; implements decision tree classifier
# from sklearn.externals import joblib #used for saving and loading modules
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
music_data = pd.read_csv('music.csv')
from sklearn import tree
X = music_data.drop(columns = ['genre']) #creates new dataset that drops the specified column
y = music_data['genre'] #grabs the genre column from music_data
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=1) #returns more than one value, so we make it multiple variables
#^^ first two values are for training and testing, and last two are the output sets for training and testing;
# X is the data we are working with, y is the target data we want to use, test_size is the size of the dataset
model = DecisionTreeClassifier() #model variable set to new instance of DecisionTreeClassifier
model.fit(X_train,y_train) #takes two arguments: input set and output set; in our classifier, we want to use both X(our data) and y(what we are referencing to predict)
#what fit() does is that its able to use the first dataset as a reference and the second dataset is used to compare the values and predict what the outcome will be
# joblib.dump(model, 'music-recommender.joblib') #we choose what file we want to dump and what we want to call that file
predictions = model.predict(X_test) #takes a two dimensional array, each inner array are the parameters set to be taken. For this example, we want our model to predict
#X_test contains the inputs so we don't have to pass the array
#what a 21 year old male (1) likes and what a 22 year old female (0) likes
# predictions
# score = accuracy_score(y_test, predictions)
# y_test
tree.export_graphviz(model, out_file='music-recommender.dot', feature_names=['age', 'gender'], class_names=sorted(y.unique()), label='all',rounded = True, filled=True)

ImportError: cannot import name 'joblib' from 'sklearn.externals' (c:\Users\CollinThao\anaconda3\Lib\site-packages\sklearn\externals\__init__.py)

In [90]:
X_train

    age  gender
17   35       0
5    30       1
2    25       1
4    29       1
3    26       1
10   21       0
9    20       0
15   31       0
6    31       1
8    37       1
13   27       0
7    33       1
16   34       0
0    20       1
1    23       1
14   30       0
11   25       0